### ISSUE TITLE
Search paths not added to QGIS for local zipped repositories

### ISSUE THREAD

**Issue by dude1756** [QGIS-Contribution/QGIS-ResourceSharing#105]
Hi,

I'm using QGIS 3.12 and installed resource sharing plugin 0.12.0. Thanks to your nice documentation setting up an own repository was quite easy and I can also successfully install i.e. a svg collection. However, a search path to new local resource sharing folder is not added automatically in QGIS. Same for models, etc. Am I missing sth. or shouldn't this be done automatically? I can find installed ressources in subfolders of %userprofile%\QGIS\Resource Sharing.
Would be great if you have some hints for me.

Thanks.

**Comment by havatv** [comment]
Search paths should be set up for SVG. Symbols (XML files) should be included in the default style. For Layer styles (QML), the paths will be updated. Models, R scripts and processing scripts should be installed in their Processing folders, so that they become available in the Processing Toolbox.

If you experience problems with your "test" repository, and it is available for testing, I could test it if you provide the URL.

**Comment by dude1756** [comment]
@havatv , thx. for your reply. Well, it's getting a bit weired. As I use a private repository on an on premise sever I've created a test repository here on github (https://github.com/dude1756/test.git). This one works as expected (svg path is added to QGIS search path). However, when I use same files and folders on my private server, installing a collection via your plugin expects a zip file to be downloaded (in this case osm.zip). If a provide a zip file it will be installed but search path is not added. Any idea?

**Comment by havatv** [comment]
@dude1756, thanks for following up.  I will try to check if there are problems with zip files.

**Comment by dude1756** [comment]
Thx. Just to to get it right, I do not understand why a local folder structure without zip cannot be installed and why a zip is expected here. Is this by purpose?

**Comment by havatv** [comment]
I zipped your github repository and unzipped it in my local file system (folder `/home/ht/tests/test-master`). After adding the repository using `file:/home/ht/tests/test-master` for URL, the collection was added under `resource_sharing/collections` in my QGIS user profile folder, and the SVGs became available when choosing *SVG Marker* for *Symbol layer type* in Symbology:

![image](https://user-images.githubusercontent.com/1598812/78277920-8dae6100-7515-11ea-8fdd-107c9ad2e977.png)

The issue you have experienced might be due to the change in the default location for the collections. It was moved from `%userprofile%\QGIS\Resource Sharing` to `resource_sharing/collections` under the QGIS user profile in version (it was done in version 0.10.0).
Sorry about that.

Could you try to remove all traces of the plugin (uninstall the plugin itself, remove  the `%userprofile%\QGIS\Resource Sharing` directory and the `resource_sharing` directory under your QGIS user dir), and then install version 0.12.0 again, and check if the problem persists?

**Comment by dude1756** [comment]
Unfortunately it doesn't help. Still search path is not added here:
![image](https://user-images.githubusercontent.com/31192919/78281999-de28bd00-751b-11ea-8797-9e6701a5ac0e.png)
I get a message that installation of this (zipped) collection has been successful but it is not added to `resource_sharing/collections`.
When I use my test repository on github it works:
![image](https://user-images.githubusercontent.com/31192919/78282202-2ba52a00-751c-11ea-8ce7-983ff34310f7.png)
And repository is added to `resource_sharing/collections`

So, as you have expected, sth. is going wrong with zipped collections.

**Comment by havatv** [comment]
Sorry, I was to to fast here... I thought you were trying to use zipped collections for a local file system repository. My mistake!
Knowing better now, I will test with a server solution ...

Since I was following the local file system track, I tried to find out how zipped collections are supposed to be handled (I started to maintain this plugin a month ago, so I still don't have the complete picture of how it works). It seems as if zipped collections are only available for network resources accessed through http/https.  So local file system repositories can not contain zipped collections. I will update the documentation to make that more clear.

**Comment by havatv** [comment]
@dude1756, for zipped collections to work, the directory and file structure on the server must be exactly as described in the current documentation. I just updated the documentation: http://qgis-contribution.github.io/QGIS-ResourceSharing/author/creating-repository.html, since it turned out to be vague and slightly misleading. Could you try to follow the instructions in the current documentation (**Your Own Server**), and see if that works?
Note that the plugin requires a trailing slash for the repository URL:

![image](https://user-images.githubusercontent.com/1598812/78309056-527a5500-754a-11ea-84f9-33e8c24549ca.png)

**Comment by dude1756** [comment]
@havatv , Thanks for updating documentation. I've checked everything again and indeed, trailing slash for repository URL was missing. However, this does no difference and it doesn't work. In my case still a new folder QGIS is created here `%userprofile%\QGIS\Resource Sharing` and I can find unzipped collection here. As you said, this directory shouldn't exist anymore and it is not used for my git test repository. So, could it be that "collection_path" in resource_sharing/repository_handler/remote_zip_handler.py](url) is not set correctly? I'm not a programmer but just following bread crums leading me to anything related to ".zip". Does it work for you? Is this old folder  `%userprofile%\QGIS\Resource Sharing` also created and new folder path `resource_sharing/collections`? Last one is not created on my side which I guess is the problem.

**Comment by havatv** [comment]
@dude1756, thanks again for testing!
When changing the default file system location for collections, a setting (`localCollectionDir` under `[ResourceSharing]`) was added to control that location (check the documentation for details - http://qgis-contribution.github.io/QGIS-ResourceSharing/user/plugin-configuration.html). And I think I the value of that setting was set to the old location if the user had collections there.  Since you are experiencing problems, I guess that this setting value is not used properly when determining the user's collection location. I will look into it.

**Comment by dude1756** [comment]
@havatv, you'r right, this `localCollectionir` value was set to the old path and uninstalling the plugin is not sufficient to change this. So, after uninstalling and deleting complete section for resource sharing in QGIS3.ini file and installing the plugin again, new path is set correctly. Now, I can find unzipped collection here (as intended): `%appdata%\QGIS\QGIS3\profiles\default\resource_sharing\collections\f6959e8730b521512bf36ba3a14bc0f1e9265c27`. However, still no search path to this directory is added in QGIS. Sth. is handled differently compared to a git repository.

**Comment by havatv** [comment]
Regarding search paths. The SVG search path will only be updated with the collection "root" directory (and that should be the directory given in `localCollectionDir`). So navigation in the *SVG Groups* widget is rather messy when you have many installed collections (all the collection IDs appear as "root" groups under "User Symbols").
Do you see your SVGs in the *SVG Groups* widget when you have chosen *SVG Marker* for *Symbol layer type* in layer Symbology?

**Comment by dude1756** [comment]
Hi, maybe I was too unprecise regarding my previous comment.
This search path `%appdata%/QGIS/QGIS3\profiles\default/resource_sharing\collections` is added to QGIS when I use my test collection on github. Then, for sure, SVG show up in SVG Groups widget. However, when I use zipped collection on my server, collection is unzipped in another subfolder of `%appdata%/QGIS/QGIS3\profiles\default/resource_sharing\collections`.  So far behaviour for both approaches is the same. However, after installing a zipped collection from my server search path is not added and SVG do **NOT** show up in SVG Groups widget.

**Comment by havatv** [comment]
Two questions:

1. What does your SVG search path look like after you have installed the zipped collection?
2. What is the contents of the "another subfolder", and where in the file system is it located?

**Comment by dude1756** [comment]
Regarding 1) It's my standard search path, so nothing is added: https://user-images.githubusercontent.com/31192919/78281999-de28bd00-751b-11ea-8797-9e6701a5ac0e.png
=> when I use github repository it's this:
![image](https://user-images.githubusercontent.com/31192919/78356324-9fdcdd80-75af-11ea-8a59-77071b731381.png)

Regarding 2)
This is for github test collection:
%appdata%\QGIS\QGIS3\profiles\default\resource_sharing\collections\c67c3e1748184e8920ec7883c5845db02d793632\svg
This is for zip collection:
%appdata%\QGIS\QGIS3\profiles\default\resource_sharing\collections\f6959e8730b521512bf36ba3a14bc0f1e9265c27\osm\svg

And while I'm writing this I'm recognizing my mistake :-( I've zipped my collection with another folder inside with the collection name - ARRGH. Now it works after deleting that folder inside the zip file. Reading manuals carefully is so important! Thanks for your patience and support.

**Comment by havatv** [comment]
Glad to hear that this has been resolved. And thank you again for bringing this up! You have helped improve the documentation considerably (and helped me get a better understanding of zipped collections.
Please don't hesitate to add documentation issues if you think the documentation could be improved.
Closing this issue.
