### ISSUE TITLE
Installing plugin from local repository

### ISSUE THREAD

**Issue by dude1756** [QGIS-Contribution/QGIS-ResourceSharing#125]
Hi havatv, it's me again :-)
With latest version I'm facing a problem to provide it from a local repository instead downloading it from QGIS official repository. In previous versions I could just zip this downloaded plugin folder and provide it locally. Now can be installed but I get an error message in QGIS saying that plugin cannot be found but is probably installed.
Any hints?
Thanks!

**Comment by havatv** [comment]
Hi again, @dude1756.

To install the plugin without going through the the official QGIS plugin repository, you can download the plugin as a zip-file (for example https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/master.zip), and then unzip it in you local plugin directory (python/plugins under your QGIS user directory).
The plugin will now be available in a new directory (e.g. `QGIS-ResourceSharing-master`, if you downloaded the master branch). Since this is not the same directory name as when installing from plugins.qgis.org, you better remove the `qgis_resource_sharing` directory from the plugin directory before starting QGIS. Then, go to the plugin manager, and re-enable the plugin.

**Comment by dude1756** [comment]
Hi havatv,
thx. Sometimes a bit confusing behaviour when you delete and reinstall different version. It finally works.
