### ISSUE TITLE
Error parsing metadata: 'utf8' codec can't decode byte '0xe4' in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by johannesherburger** [QGIS-Contribution/QGIS-ResourceSharing#41]
Hello everyone,

i wanted to install the QGIS resource sharing plugin, but received the following error message: Error parsing metadata: 'utf8' codec can't decode byte '0xe4' in position 0: invalid continuation byte

can anyone help me out with that?

cheers
Johannes

**Comment by akbargumbira** [comment]
On what OS are you on? Could you check the Log Message Panel (View->Panel->Log Message Panel) and copy here the more detailed error? Cheers

**Comment by MoStorm** [comment]
Hi,
I am getting the same error on a Windows 7 pc. See my detailed error message below!

Best regards,
Morten
-------------------------------
Couldn't load plugin qgis_resource_sharing due to an error when calling its classFactory() method 

MetadataError: Error parsing metadata: 'utf8' codec can't decode byte 0xe4 in position 0: invalid continuation byte 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\__init__.py", line 58, in classFactory
    return Plugin(iface)
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\plugin.py", line 61, in __init__
    self.dlg = ResourceSharingDialog(iface=self.iface)
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\gui\resource_sharing_dialog.py", line 140, in __init__
    self.repository_manager = RepositoryManager()
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 70, in __init__
    self.load_directories()
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 126, in load_directories
    online_dir_name, self._online_directories[online_dir_name])
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\repository_manager.py", line 159, in add_directory
    collections = repo_handler.parse_metadata()
  File "C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing\resource_sharing\repository_handler\base.py", line 144, in parse_metadata
    raise MetadataError('Error parsing metadata: %s' % e)
MetadataError: Error parsing metadata: 'utf8' codec can't decode byte 0xe4 in position 0: invalid continuation byte


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.3 Las Palmas, 77b8c3d 

Python Path:
C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/morten.storm.ARTOGIS/.qgis2/python
C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PIL
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/morten.storm.ARTOGIS/.qgis2//python
C:\Users\morten.storm.ARTOGIS\.qgis2\python\plugins
C:/Source/QGIS
C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing
C:\Users\morten.storm.ARTOGIS\.qgis2\python\plugins\qgis_resource_sharing
C:\Users\morten.storm.ARTOGIS\.qgis2\python\plugins\qgis_resource_sharing\ext_libs
C:/Users/morten.storm.ARTOGIS/.qgis2/python/plugins\qgis_resource_sharing

**Comment by andreasplesch** [comment]
Perhaps related to the recently added cyrillic here ?

https://github.com/qgis/QGIS-Resources/blob/45bfdc8fa8c8b49e8cadf946eacbb6a169e615ad/collections/gis_lab/LICENSE.txt

**Comment by anitagraser** [comment]
I just added that collection and the issue was reported long before.

**Comment by andreasplesch** [comment]
Ah, yes, of course. Something else then. Please disregard.

**Comment by akbargumbira** [comment]
If only I can replicate this :( I suspect that this only happens in Windows?

**Comment by havatv** [comment]
@johannesherburger, @MoStorm, could you test the latest version of the plugin (0.12.0)? A number of updates that might be relevant to this have been made since the issue was reported, and I can't replicate the issue with QGIS 3 on neither Windows 10 nor Ubuntu 18.4.

**Comment by MoStorm** [comment]
I just installed the most recent version of the plugin - and made some quick testing. No problems so far! :-)

**Comment by havatv** [comment]
> I just installed the most recent version of the plugin - and made some quick testing. No problems so far! :-) BTW: Windows 7 and QGIS 3.10.

Thanks a lot, @MoStorm! I close the issue. Please re-open if, for some reason, you should experience this again.
