### ISSUE TITLE
Files removed from repository are still being installed from cache 

### ISSUE THREAD

**Issue by borysiasty** [QGIS-Contribution/QGIS-ResourceSharing#44]
I removed some svgs from a repository, pressed *Reload Repositories* and *Reinstall*. The removed files are still present in both `~/.qgis2/resource_sharing` and `~/QGIS/Resource Sharing` directories

**Comment by havatv** [comment]
Thanks for reporting, @borysiasty.
What is the result if you first Uninstall and then Install?

Would users always want local files to be deleted when they have been removed from a repository?
At least for scripts (R and Python Processing), files are stored in their standard location in the local file system, sharinged with scripts the user has added there.

**Comment by borysiasty** [comment]
Unfortunately I won't find any time soon to prepare a test repo and verify it.

My intention was to allow some svgs get obsolete :) Imagine a repository, where new svgs appear every few months, so it's worth to run reinstall it from time to time. And if the repo maintainer wants to remove one of the svgs for any reason (duplicate, copyright issues, ugly, whatever), I looks odd to me to not let them go. But I don't insist.

It was all about symbols and svgs, placed in separate subdirectories for each repo. If scripts land in a common directory, it's a different story of course.

**Comment by havatv** [comment]
Good points, @borysiasty. I will look more into it, but not today...

**Comment by havatv** [comment]
@borysiasty, I have looked into this. It turns out that the dulwich library (that we use for git access) currently does not support removal of files (https://github.com/dulwich/dulwich/issues/452).
I have tried a "hack" - removing the collection directory before pulling. See https://github.com/QGIS-Contribution/QGIS-ResourceSharing/pull/108
The PR was just merged into master.

It would be great if you could test:

1. download: https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/master.zip
2. unzip in your plugin directory
3. remove the directory that contains your current Resource Sharing plugin
4. (re)start QGIS
5. enable the plugin in the plugin manager
6. run

Please re-open if this does not fix the issue.
