### ISSUE TITLE
Not Able to add any GIT collections

### ISSUE THREAD

**Issue by chleidersdorff** [QGIS-Contribution/QGIS-ResourceSharing#91]
I am unable to add any of the GIT repository collections, they all fail.

![image](https://user-images.githubusercontent.com/52182284/76173726-96996480-61ed-11ea-9ad7-4a36a443c0a7.png)

**Comment by havatv** [comment]
Thank you for reporting, @chleidersdorff! Much appreciated.

There could be a problem with the `metadata.ini` file in a repository, but aborting seems like a bit of an overreaction. I will try to fix that.

Which version of the plugin are you using?

Could you try to remove all the Resource Sharing plugin stuff and install the latest version?
That means removing the `resource_sharing` folder from you QGIS user folder (`...QGIS/QGIS3/profiles/default/resource_sharing/`) and the (old) "Resource Sharing" folder under `~/QGIS/`.

I have never experienced this with any versions of the plugin on Ubuntu 18.04 (the same with Windows 10, but I have not tested much on that platform).

**Comment by chleidersdorff** [comment]
@havatv i am using version 0.11.1 installed through QGIS 10.12 plugins manager. I have tried completely removing the plugin and any other folder that says "Resource Sharing" but i still get the same errors.

here is a link i am trying to add: https://github.com/alinager/qgis-styles.git 

![image](https://user-images.githubusercontent.com/52182284/76278006-29153300-62d6-11ea-9fa7-8e1e2eb0ea57.png)

**Comment by havatv** [comment]
The repository (*Alina's Repository*) that you try to load is listed in the official QGIS resources directory and should be loaded automatically by the plugin. The repository loads fine here, and I can install its collections (*Animal silhouettes* and *Animal tracks and signs*).

The error message (that comes from the Python *configparser*) is unexpected, since the metadata.ini file (https://github.com/alinager/qgis-styles/blob/master/metadata.ini) looks fine.
So I guess that for some reason this the plugin is not able to fetch the metadata.ini file of the repository.

Could the reason for this be network trouble?
Can you open the URL (https://github.com/alinager/qgis-styles/blob/master/metadata.ini)?
Are you behind a proxy?
Anything else that might be causing this?

You could try the branch with the updated dulwich version - see #40 for details on how to install that branch (dulwich is used for fetching git repositories).

**Comment by chleidersdorff** [comment]
Hi @havatv 

I am on a corporate network, so a proxy could be used, not sure. I am however able to access the ini file you mentioned and if i add the Atilio's Repository it works fine.

![image](https://user-images.githubusercontent.com/52182284/76366131-d5a5f200-6374-11ea-91da-ad899de51c15.png)

**Comment by havatv** [comment]
Thanks for your patience, @chleidersdorff!

A difference between the two repositories is that *Atilio's Repository* is "pure" HTTP, while *Alina's Repository* is github (and HTTPS).
Did you test the master branch of the plugin (it contains an update of the software that is used for accessing GitHub repositories)?

Is this your workflow?
1. Remove all traces of the plugin (`<QGIS user path>/resource_sharing` + `<home>/QGIS/Resource Sharing`)
2. Get the master branch of the plugin (https://github.com/QGIS-Contribution/QGIS-ResourceSharing/archive/master.zip)
3. Unzip it in the plugins folder
4. (Re)start QGIS.
5. Run the Resource Sharing plugin
6. Go to the Settings tab and push the **Reload Repositories** button

**Comment by havatv** [comment]
@chleidersdorff, version 0.12.0 of the plugin is now out. It has a more recent Dulwich version and also some other fixes that might be relevant to this issue.
Could you try with the new version?
Also, are you sure that you specified `https`, and not `http` for the link to Alina's Repository? Using http instead of https for github repositories is known to cause problems.

**Comment by havatv** [comment]
Hi again, @chleidersdorff.

I am not sure what the problem can be. Could you try the following:

1. Uninstall the plugin.
2. Go to your QGIS user directory (`~/.local/share/QGIS/QGIS3/profiles/default` on Linux, `C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default` on Windows) and remove the `resource_sharing` directory (that contains all repositories and collections).
3. Install the latest version of the plugin
4. Start the plugin
5. Go to *Settings* and press the *Reload Repositories* button
6. Go to *All collections* - hopefully you will now see a lot of collections (similar to the screenshot in http://qgis-contribution.github.io/QGIS-ResourceSharing/)
7. Try to *Install* the *Animal silhouettes (Alina's Repository)* collection

**Comment by havatv** [comment]
> ![image](https://user-images.githubusercontent.com/52182284/76366131-d5a5f200-6374-11ea-91da-ad899de51c15.png)

I am a little confused by the fact that the officially approved QGIS repositories are missing in the *Collection Repositories* list in the ***Settings*** tab. After pressing *Reload repositories* there should be a list of approved QGIS resource sharing repositories, as in http://qgis-contribution.github.io/QGIS-ResourceSharing/user/adding-repository.html 
Have you tried *Reload repositories*? What is the effect?

**Comment by havatv** [comment]
Since it is not possible to replicate this issue, I close it.  Please re-open with more information if the issue persists.
